const sidebarTranslations = {
  en: {
    analyticalChemist: "Analytical Chemist",
    webDeveloper: "Web Developer",
    showContacts: "Show Contacts",
    github: "GitHub",
    linkedin: "LinkedIn",
    currentLocation: "Current Location",
    location: "Spain",
    languageSelector: "Language Selector",
    email: "Email",
    mailTo: "Send Email",
  },
  es: {
    analyticalChemist: "Químico Analítico",
    webDeveloper: "Desarrollador Web",
    showContacts: "Mostrar Contactos",
    github: "GitHub",
    linkedin: "LinkedIn",
    currentLocation: "Ubicación Actual",
    location: "España",
    languageSelector: "Selector de Idioma",
    email: "Correo Electrónico",
    mailTo: "Enviar Correo",
  },
  de: {
    analyticalChemist: "Analytischer Chemiker",
    webDeveloper: "Webentwickler",
    showContacts: "Kontakte anzeigen",
    github: "GitHub",
    linkedin: "LinkedIn",
    currentLocation: "Aktueller Standort",
    location: "Spanien",
    languageSelector: "Sprachauswahl", 
    email: "E-Mail",
    mailTo: "E-Mail senden",
  },
  pt: {
    analyticalChemist: "Químico Analítico",
    webDeveloper: "Desenvolvedor Web",
    showContacts: "Mostrar Contatos",
    github: "GitHub",
    linkedin: "LinkedIn",
    currentLocation: "Localização Atual",
    location: "Espanha",
    languageSelector: "Seletor de Idioma",
    email: "Email",
    mailTo: "Enviar Email",
  },
};

export { sidebarTranslations };
